#!/usr/bin/env python3
"""Rebuild the canonical fear-greed.csv.

Concatenates the frozen pre-2021 archive with the freshly fetched CNN tail.
On overlap, CNN wins (it's authoritative from 2021-02-01 onward).

Inputs:
  datasets/archive/fear-greed-pre-2021.csv   (static, checked in)
  datasets/cnn_fear_greed.csv                (generated by fetch_cnn.py)

Output:
  fear-greed.csv                             (canonical, at repo root)

Aborts on sanity-check failure rather than writing a bad file:
  - combined is shorter than the archive alone
  - last date is > 7 days stale
  - duplicate dates in the combined output
"""
from __future__ import annotations

import sys
from datetime import date, timedelta
from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parent.parent
ARCHIVE_PATH = REPO_ROOT / "datasets" / "archive" / "fear-greed-pre-2021.csv"
CNN_PATH = REPO_ROOT / "datasets" / "cnn_fear_greed.csv"
OUTPUT_PATH = REPO_ROOT / "fear-greed.csv"

STALENESS_LIMIT_DAYS = 7


def load_inputs() -> tuple[pd.DataFrame, pd.DataFrame]:
    if not ARCHIVE_PATH.exists():
        raise FileNotFoundError(f"Missing archive: {ARCHIVE_PATH}")
    if not CNN_PATH.exists():
        raise FileNotFoundError(f"Missing CNN CSV: {CNN_PATH}. Run fetch_cnn.py first.")

    archive = pd.read_csv(ARCHIVE_PATH)
    cnn = pd.read_csv(CNN_PATH)

    # Archive has integer scores; CNN has floats. Promote archive to float
    # so concat produces a single-dtype column.
    archive["Fear Greed"] = archive["Fear Greed"].astype(float)
    archive["Rating"] = ""

    return archive, cnn


# Cutoffs derived empirically from CNN's own labels in
# datasets/cnn_fear_greed.csv. The band boundaries on the CNN side use
# a half-open pattern: [0,25) extreme fear, [25,45) fear, [45,55) neutral,
# [55,75) greed, [75,100] extreme greed.
def rating_for(score: float) -> str:
    if score < 25:
        return "extreme fear"
    if score < 45:
        return "fear"
    if score < 55:
        return "neutral"
    if score < 75:
        return "greed"
    return "extreme greed"


def combine(archive: pd.DataFrame, cnn: pd.DataFrame) -> pd.DataFrame:
    combined = pd.concat([archive, cnn], ignore_index=True)
    # CNN wins on duplicate dates (it appears second, so keep=last).
    combined = combined.drop_duplicates(subset=["Date"], keep="last")
    combined = combined.sort_values("Date", kind="stable").reset_index(drop=True)

    # Fill Rating for archive rows (CNN labels are authoritative and preserved).
    combined["Rating"] = combined["Rating"].fillna("").astype(str)
    blank = combined["Rating"].eq("")
    combined.loc[blank, "Rating"] = combined.loc[blank, "Fear Greed"].apply(rating_for)

    return combined


def sanity_check(combined: pd.DataFrame, archive_len: int) -> None:
    if len(combined) < archive_len:
        raise RuntimeError(
            f"Combined ({len(combined)} rows) is shorter than archive ({archive_len}). "
            "Refusing to write."
        )

    dupes = combined[combined["Date"].duplicated()]
    if not dupes.empty:
        raise RuntimeError(f"Duplicate dates in combined output:\n{dupes}")

    last_date = date.fromisoformat(combined["Date"].iloc[-1])
    age = (date.today() - last_date).days
    if age > STALENESS_LIMIT_DAYS:
        raise RuntimeError(
            f"Last date {last_date} is {age} days old (limit {STALENESS_LIMIT_DAYS}). "
            "CNN feed may be broken."
        )


def main() -> int:
    archive, cnn = load_inputs()
    combined = combine(archive, cnn)
    sanity_check(combined, len(archive))

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    combined.to_csv(OUTPUT_PATH, index=False)

    print(f"Wrote {len(combined)} rows to {OUTPUT_PATH.relative_to(REPO_ROOT)}")
    print(f"Range: {combined['Date'].iloc[0]} -> {combined['Date'].iloc[-1]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
